var precioJuego = 39.99; 
var contenido = {"titulo": "<h1> EUROPA UNIVERSALIS IV </h1>", 
            "valorPrecio" : "<h3>$39.99 USD</h3>", 
            "contenidoDetalle":'<div class="detallewrapper"> <h4>VALORACIÓN</h4> <p>6</p> </div> <div class="detallewrapper"> <h4>GÉNERO</h4> <p>Simulation, Strategy</p> </div> <div class="detallewrapper"> <h4>DEVELOPER</h4> <p>Paradox Development Studio</p> </div> <div class="detallewrapper"> <h4>PUBLISHER</h4> <p>Paradox Interactive</p> </div>',
            "descripcion": '<div class="descripcionwrapper"> <div> <h4>DESCRIPCIÓN</h4> <p><b>Fulfill Your Quest For Global Domination</b></p> <p>Paradox Development Studio is back with the fourth installment of the award-winning Europa Universalis series. The empire building game Europa Universalis IV gives you control of a nation to guide through the years in order to create a dominant global empire. Rule your nation through the centuries, with unparalleled freedom, depth and historical accuracy. True exploration, trade, warfare and diplomacy will be brought to life in this epic title rife with rich strategic and tactical depth.</p> <p><b>You begin with three survivors of a shipwreck on a distant world.</b></p> </div> <div><button class="botonleermas" id="botonleermas" onclick="leerMas()"><b>Leer más</b></button></div> <div id="leermas" style="display: none"> <p><b>Main Features</b></p><ul class="list"> <li><b>Make your own decisions</b><br>Nation building is completely flexible and the possibilities are endless.</li> <li><b>Use your Monarch Power</b><br>Experience the new system of monarch power where your choices are influenced by the caliber of the man or woman you have at the top and will direct the ebb and flow of gameplay.</li> <li><b>Experience history coming to life</b><br>The great personalities of the past are on hand to support you as you make your mark on thousands of historical events.</li> <li>Turn the world into your playground: Enjoy hundreds of years of gameplay in a lush topographical map complete with dynamic seasonal effects. </li> <li><b>Experience the all new trade system</b>The trade system adds a new dimension to the great trade empires of the period. Gain control of vital trade routes and make the wealth of the world flow to your coffers. </li> <li><b>Bring out your negotiating skills in a deeper diplomatic system</b><br>Use coalitions, royal marriages and support for rebels and explore the possibilities of the new unilateral opinion system. </li> <li><b>Engage in Cross-platform Multiplayer</b><br>Battle against your friends or try the co-operative multiplayer mode that allows several players to work together to control a single nation with up to 32 players. Featuring improved chat and new matchmaking servers. </li> <li><b>Create your own history & customize your game</b><br>Europa Universalis IV gives you the chance to customize and mod practically anything your heart may desire and uses Steam Workshop. </li></ul> <p><i>Paradox Interactive, EUROPA UNIVERSALIS® Copyright© [2013] Paradox Interactive AB All rights reserved. www.paradoxplaza.com<i></p> <button class="botonleermas" id="botonleermenos" onclick="leerMas()"><b>Mostrar menos</b></button> </div> </div>',
            "fotos" : [{"foto1"  : '<img src="img/Europa_Universalis_IV/desc_001.jpg" alt="Europa Universalis IV">'},
                        {"foto2" : '<img src="img/Europa_Universalis_IV/desc_002.jpg" alt="Europa Universalis IV">'},
                        {"foto3" : '<img src="img/Europa_Universalis_IV/desc_003.jpg" alt="Europa Universalis IV">'},
                        {"foto4" : '<img src="img/Europa_Universalis_IV/desc_004.jpg" alt="Europa Universalis IV">'},
                        {"foto5" : '<img src="img/Europa_Universalis_IV/desc_005.jpg" alt="Europa Universalis IV">'},
                        {"bannerPrecio" : '<img src="img/Europa_Universalis_IV/europa_banner.jpg" alt="Europa Universalis IV" style="width: 100%">'}
                    ]
            
            }