var precioJuego = 59.99; 
var contenido = {"titulo": "<h1> KINGDOM COME: DELIVERANCE </h1>", 
            "valorPrecio" : "<h3>$59.99 USD</h3>", 
            "contenidoDetalle":'<div class="detallewrapper"> <h4>VALORACIÓN</h4> <p>7</p> </div> <div class="detallewrapper"> <h4>GÉNERO</h4> <p>Action, Adventure, RPG</p> </div> <div class="detallewrapper"> <h4>DEVELOPER</h4> <p>Warhorse Studios</p> </div> <div class="detallewrapper"> <h4>PUBLISHER</h4> <p>Warhorse Studios</p> </div>',
            "descripcion": '<div class="descripcionwrapper"> <div> <h4>DESCRIPCIÓN</h4> <p><b>Game:</b><br> You are Henry, the son of a blacksmith. Thrust into a raging civil war, you watch helplessly as invaders storm your village and slaughter your friends and family. Narrowly escaping the brutal attack, you grab your sword to fight back. Avenge the death of your parents and help repel the invading forces! </p> </div> <div><button class="botonleermas" id="botonleermas" onclick="leerMas()"><b>Leer más</b></button></div> <div id="leermas" style="display: none"> <p><b>Story:</b><br> Bohemia – located in the heart of Europe, the region is rich in culture, silver, and sprawling castles. The death of its beloved ruler, Emperor Charles IV, has plunged the kingdom into dark times: war, corruption, and discord are tearing this jewel of the Holy Roman Empire apart. </p> <p>One of Charles’ sons, Wenceslas, has inherited the crown. Unlike his father, Wenceslas is a naive, self-indulgent, unambitious monarch. His half-brother and King of Hungary, Sigismund the Red Fox, senses weakness in Wenceslas. Feigning good will, Sigismund travels to Bohemia and kidnaps his half-brother. With no king on the throne, Sigismund is now free to plunder Bohemia and seize its riches.</p> <p>In the midst of this chaos, you’re Henry, the son of a blacksmith. Your peaceful life is shattered when a mercenary raid, ordered by King Sigismund himself, burns your village to the ground. By bittersweet fortune, you are one of the sole survivors of this massacre. </p> <p>Without a home, family, or future you end up in the service of Lord Radzig Kobyla, who is forming a resistance against the invasion. Fate drags you into this bloody conflict and shoves you into a raging civil war, where you help fight for the future of Bohemia.</p><p><b>Features:</b></p><ul class="list"> <li>Massive realistic open world: Majestic castles, vast fields, all rendered in stunning high-end graphics.</li> <li>Non-linear story: Solve quests in multiple ways, then face the consequences of your decisions.</li> <li>Challenging combat: Distance, stealth, or melee. Choose your weapons and execute dozens of unique combos in battles that are as thrilling as they are merciless.</li> <li>Character development: Improve your skills, earn new perks, and forge and upgrade your equipment.</li> <li>Dynamic world: Your actions influence the reactions of the people around you. Fight, steal, seduce, threaten, persuade, or bribe. It’s all up to you.</li> <li>Historical accuracy: Meet real historical characters and experience the genuine look and feel of medieval Bohemia.</li> </ul> <button class="botonleermas" id="botonleermenos" onclick="leerMas()"><b>Mostrar menos</b></button> </div> </div>',
            "fotos" : [{"foto1"  : '<img src="img/Kingdom_Come/kcd_001.jpg" alt="Kingdom Come: Deliverance">'},
                        {"foto2" : '<img src="img/Kingdom_Come/kcd_002.jpg" alt="Kingdom Come: Deliverance">'},
                        {"foto3" : '<img src="img/Kingdom_Come/kcd_003.jpg" alt="Kingdom Come: Deliverance">'},
                        {"foto4" : '<img src="img/Kingdom_Come/kcd_004.jpg" alt="Kingdom Come: Deliverance">'},
                        {"foto5" : '<img src="img/Kingdom_Come/kcd_005.jpg" alt="Kingdom Come: Deliverance">'},
                        {"bannerPrecio" : '<img src="img/Kingdom_Come/kingdomcome_banner.jpg" alt="Kingdom Come: Deliverance" style="width: 100%">'}
                    ]
            
            }