var precioJuego = 19.99; 
var contenido = {"titulo": "<h1> METAL GEAR SOLID V: THE PHANTOM PAIN </h1>", 
            "valorPrecio" : "<h3>$19.99 USD</h3>", 
            "contenidoDetalle":'<div class="detallewrapper"> <h4>VALORACIÓN</h4> <p>8</p> </div> <div class="detallewrapper"> <h4>GÉNERO</h4> <p>Action, Adventure</p> </div> <div class="detallewrapper"> <h4>DEVELOPER</h4> <p>Konami Digital Entertainment, Inc.</p> </div> <div class="detallewrapper"> <h4>PUBLISHER</h4> <p>Konami Digital Entertainment, Inc.</p> </div>',
            "descripcion": '<div class="descripcionwrapper"> <div> <h4>DESCRIPCIÓN</h4> <p>Konami Digital Entertainment continues forth the ‘METAL GEAR SOLID V Experience’ with the latest chapter, METAL GEAR SOLID V: The Phantom Pain. Ushering in a new era for the franchise with cutting-edge technology powered by the Fox Engine, MGSV: The Phantom Pain will provide players a first-rate gaming experience as they are offered tactical freedom to carry out open-world missions.</p> </div> <div><button class="botonleermas" id="botonleermas" onclick="leerMas()"><b>Leer más</b></button></div> <div id="leermas" style="display: none"> <p>Nine years after the events of MGSV: GROUND ZEROES and the fall of Mother Base, Snake a.k.a. Big Boss, awakens from a nine year coma. The year is 1984. The Cold War serves as the backdrop as nuclear weapons continue to shape a global crisis. Driven by revenge, Snake establishes a new private army and returns to the battlefield in pursuit of the shadow group, XOF.</p> <p>The METAL GEAR SOLID team continues to ambitiously explore mature themes such as the psychology of warfare and the atrocities that result from those that engage in its vicious cycle. One of the most anticipated games of the year with its open-world design, photorealistic visual fidelity and feature-rich game design, MGSV: The Phantom Pain will leave its mark as one of the hallmarks in the gaming industry for its cinematic storytelling, heavy themes, and immersive tactical gameplay.</p><p><b>Key features:</b></p><ul class="list"> <li>Open-World game design allowing players ultimate freedom on how to approach missions and overall game progression</li> <li>Fox Engine delivers photorealistic graphics, thoughtful game design and true new-generation game production quality</li> <li>Online connectivity that carries the experience beyond the consoles to other devices to augment the overall functionality and access to the game.</li> </ul> <p><i>©2015 Konami Digital Entertainment</i></p><button class="botonleermas" id="botonleermenos" onclick="leerMas()"><b>Mostrar menos</b></button> </div> </div>',
            "fotos" : [{"foto1"  : '<img src="img/Metal_Gear_Solid/mgs_001.jpg" alt="Metal Gear Solid V: The Phantom Pain">'},
                        {"foto2" : '<img src="img/Metal_Gear_Solid/mgs_002.jpg" alt="Metal Gear Solid V: The Phantom Pain">'},
                        {"foto3" : '<img src="img/Metal_Gear_Solid/mgs_003.jpg" alt="Metal Gear Solid V: The Phantom Pain">'},
                        {"foto4" : '<img src="img/Metal_Gear_Solid/mgs_004.jpg" alt="Metal Gear Solid V: The Phantom Pain">'},
                        {"foto5" : '<img src="img/Metal_Gear_Solid/mgs_005.jpg" alt="Metal Gear Solid V: The Phantom Pain">'},
                        {"bannerPrecio" : '<img src="img/Metal_Gear_Solid/mgs_banner.jpg" alt="Metal Gear Solid V: The Phantom Pain" style="width: 100%">'}
                    ]
            
            }