var precioJuego = 19.99; 
var contenido = {"titulo": "<h1> THE ELDER SCROLLS V: SKYRIM </h1>", 
            "valorPrecio" : "<h3>$19.99 USD</h3>", 
            "contenidoDetalle":'<div class="detallewrapper"> <h4>VALORACIÓN</h4> <p>9</p> </div> <div class="detallewrapper"> <h4>GÉNERO</h4> <p>RPG</p> </div> <div class="detallewrapper"> <h4>DEVELOPER</h4> <p>Bethesda Game Studios</p> </div> <div class="detallewrapper"> <h4>PUBLISHER</h4> <p>Bethesda Softworks</p> </div>',
            "descripcion": '<div class="descripcionwrapper"> <div> <h4>DESCRIPCIÓN</h4> <p><b>EPIC FANTASY REBORN</b></p> <p>The next chapter in the highly anticipated Elder Scrolls saga arrives from the makers of the 2006 and 2008 Games of the Year, Bethesda Game Studios. Skyrim reimagines and revolutionizes the open-world fantasy epic, bringing to life a complete virtual world open for you to explore any way you choose.</p> </div> <div><button class="botonleermas" id="botonleermas" onclick="leerMas()"><b>Leer más</b></button></div> <div id="leermas" style="display: none"> <p><b>LIVE ANOTHER LIFE, IN ANOTHER WORLD</b><br>Play any type of character you can imagine, and do whatever you want; the legendary freedom of choice, storytelling, and adventure of The Elder Scrolls is realized like never before.</p> <p><b>ALL NEW GRAPHICS AND GAMEPLAY ENGINE</b><br> Skyrim’s new game engine brings to life a complete virtual world with rolling clouds, rugged mountains, bustling cities, lush fields, and ancient dungeons. </p> <p><b>YOU ARE WHAT YOU PLAY</b><br>Choose from hundreds of weapons, spells, and abilities. The new character system allows you to play any way you want and define yourself through your actions.</p> <p><b>DRAGON RETURN</b>Battle ancient dragons like you’ve never seen. As Dragonborn, learn their secrets and harness their power for yourself.</p> <p><i>© 2011 Bethesda Softworks LLC, a ZeniMax Media company. The Elder Scrolls, Skyrim, Bethesda, Bethesda Game Studios, Bethesda Softworks, ZeniMax and related logos are registered trademarks or trademarks of ZeniMax Media Inc. in the U.S. and/or other countries. All other trademarks and trade names are the properties of their respective owners. All Rights Reserved. </i></p> <button class="botonleermas" id="botonleermenos" onclick="leerMas()"><b>Mostrar menos</b></button> </div> </div>',
            "fotos" : [{"foto1"  : '<img src="img/The_Elder_Scrolls/tes_001.jpg" alt="The Elder Scrolls V: Skyrim">'},
                        {"foto2" : '<img src="img/The_Elder_Scrolls/tes_002.jpg" alt="The Elder Scrolls V: Skyrim">'},
                        {"foto3" : '<img src="img/The_Elder_Scrolls/tes_003.jpg" alt="The Elder Scrolls V: Skyrim">'},
                        {"foto4" : '<img src="img/The_Elder_Scrolls/tes_004.jpg" alt="The Elder Scrolls V: Skyrim">'},
                        {"foto5" : '<img src="img/The_Elder_Scrolls/tes_005.jpg" alt="The Elder Scrolls V: Skyrim">'},
                        {"bannerPrecio" : '<img src="img/The_Elder_Scrolls/tes_banner.jpg" alt="The Elder Scrolls V: Skyrim" style="width: 100%">'}
                    ]
            
            }